In [3]:
import sys

import pandas as pd
import numpy as np
import datetime as dt
import matplotlib.pyplot as plt

In [11]:
df = pd.read_csv("../data/eth_level1_data.csv")

,Date,Price,Market Cap,Volume,Active Addresses,Daily Transactions,Twitter Followers,Weekly Commits Core,Weekly Commits Sub,Weekly Devs Core,Weekly Devs Sub,Total Value Locked,Price Bitcoin
0,2019-01-01,131.458725,13677300455,1822123555,197884,439671,436712,3556,20191,360,1415,4.693199e+05,3692.531566
1,2019-01-02,138.144802,14392313037,1831181165,236218,578127,436826,3556,20191,360,1415,4.826038e+05,3794.264254
2,2019-01-03,152.860453,15922214147,2970382678,255779,584817,436888,3556,20191,360,1415,5.256597e+05,3872.172184
3,2019-01-04,146.730599,15277722819,2147721864,224211,538193,436790,3556,20191,360,1415,2.743696e+08,3776.525808
4,2019-01-05,153.056567,15940848170,2802750465,213003,502800,437378,3556,20191,360,1415,2.892192e+08,3815.268080
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1456,2022-12-27,1226.253415,147697269148,3071221734,398821,1021604,3071090,989,6719,238,947,2.363880e+10,16900.081870
1457,2022-12-28,1211.819562,146030514727,4221450707,379892,972911,3063138,989,6719,238,947,2.346818e+10,16701.840210
1458,2022-12-29,1188.728664,143241827137,5177421363,369722,941406,3061976,989,6719,238,947,2.321374e+10,16538.906090
1459,2022-12-30,1201.543106,144831301452,4174715684,376358,940640,3057942,989,6719,238,947,2.324425e+10,16644.379090
1460,2022-12-31,1199.110497,144611517916,4110733113,336884,862609,3058579,989,6719,238,947,2.317169e+10,16604.020520